import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/ui/Header'
import WelcomeScreen from "./welcomeScreen"


export default function Home() {
  return (
    <div >
      <Head>
        <title>Cocktail App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WelcomeScreen />
    </div>
    

    
  )
}
